
box: debian/stretch64

prefix_node: 'rozo'

ram: 1024
cpuexecutioncap: 25

nb_nodes: 4

# Private Networks
networks: ['10.0.0.1']

## Devices Settings

# Export device only on 2 first nodes
export_device: { directory: './tmp', size: 40, ctrl: 'SATA Controller', port: 1, device: 0 }

# Storage devices on all nodes
stor_devices: 
- { directory: './tmp', size: 40, ctrl: 'SATA Controller', port: 2, device: 0 }
