
box: ubuntu/trusty64

prefix_node: 'trusty-node-'

ram: 1024
cpuexecutioncap: 60

nb_nodes: 4

# Private Networks
networks: ['192.168.100.4','192.168.101.4']

## Devices Settings

# Export device only on 2 first nodes
export_device:	{ directory: './tmp', size: 40, ctrl: 'SATAController', port: 1, device: 0 }

# Storage devices on all nodes
stor_devices: 
- { directory: './tmp', size: 40, ctrl: 'SATAController', port: 2, device: 0 }
- { directory: './tmp', size: 40, ctrl: 'SATAController', port: 3, device: 0 }

