
box: chef/debian-7.8

prefix_node: 'rozo'

ram: 256
cpuexecutioncap: 25

nb_nodes: 4

# Private Networks
networks: ['192.168.100.4']

## Devices Settings

# Export device only on 2 first nodes
export_device: { directory: './tmp', size: 40, ctrl: 'IDE Controller', port: 0, device: 1 }

# Storage devices on all nodes
stor_devices: 
- { directory: './tmp', size: 40, ctrl: 'IDE Controller', port: 1, device: 0 }

